/**
 * Fix messy data: find the real table inside a messy export and repair
 * everything wrong with it in one pass.
 *
 * Real exports rarely start at A1 with one clean header row. They open with a
 * report title and a "Generated by..." line, split headings over two rows,
 * drop subtotal rows and group headings ("EUROPE") into the middle of the data,
 * type numbers as text in three regional styles, mix date formats, spell the
 * same customer three ways, and end with a footnote. `tidyTable` handles all of
 * that and reports each fix in plain language so the user can see - and switch
 * off - anything before it is applied.
 *
 * Everything above the Office.js banner is pure and unit tested in
 * tests/tidy.test.ts.
 */

import {
  columnLetter,
  createSheetWithUniqueName,
  fail,
  isBlankCell,
  loadSelectedRange,
  normalizeHeader,
  ok,
  padRow,
  plural,
  rectangularize,
  runExcel,
  uniqueName,
  writeGridWithFormats,
} from "../shared/excelHelpers";
import { CellValue, Grid, OperationResult } from "../shared/types";
import type { DataSourceRef } from "./charts";
import { dateToExcelSerial, parseFlexibleDate } from "./dataCleaning";

// ---------------------------------------------------------------------------
// Text and placeholders
// ---------------------------------------------------------------------------

const INVISIBLE = /[\u00A0\u1680\u2000-\u200D\u202F\u205F\u3000\uFEFF]/g;

/** Collapse every kind of whitespace, including the invisible ones, and trim. */
export function cleanText(value: string): string {
  return value.replace(INVISIBLE, " ").replace(/\s+/g, " ").trim();
}

const PLACEHOLDER = /^(?:-+|—|–|n\/?a|#n\/a|null|none|nil|\?+)$/i;

/** "-", "N/A", "#N/A" and friends: cells that mean "no value". */
export function isPlaceholder(value: CellValue): boolean {
  return typeof value === "string" && PLACEHOLDER.test(cleanText(value));
}

function isEmptyish(value: CellValue): boolean {
  return isBlankCell(value) || isPlaceholder(value);
}

// ---------------------------------------------------------------------------
// Numbers typed as text
// ---------------------------------------------------------------------------

export type NumberStyle = "us" | "eu";

export interface LooseNumber {
  value: number;
  percent: boolean;
  /** Currency symbol or ISO code found in the text, if any. */
  currency: string | null;
  /** True when a typo such as a letter O in place of a zero was repaired. */
  repaired: boolean;
}

/** Longest first, so "R$" is not read as "$". */
const CURRENCY_SYMBOLS = ["R$", "$", "€", "£", "¥", "₦", "₹", "₵", "₱"];
const CURRENCY_CODES = /\b(USD|EUR|GBP|NGN|CAD|AUD|ZAR|KES|GHS|INR|JPY|CHF|CNY)\b/i;

/**
 * Apply a decimal convention to a string of digits and separators.
 * "us": 1,234.56   "eu": 1.234,56
 */
function digitsToNumber(text: string, style: NumberStyle): number | null {
  const hasComma = text.includes(",");
  const hasDot = text.includes(".");
  let decimal: "," | "." | null = null;

  if (hasComma && hasDot) {
    decimal = text.lastIndexOf(",") > text.lastIndexOf(".") ? "," : ".";
  } else if (hasComma) {
    const parts = text.split(",");
    if (parts.length === 2) {
      // "1,234" is a thousands group in US style; "12,5" is a decimal anywhere.
      decimal = style === "eu" || parts[1].length !== 3 ? "," : null;
    }
  } else if (hasDot) {
    const parts = text.split(".");
    if (parts.length === 2) {
      decimal = style === "eu" && parts[1].length === 3 ? null : ".";
    }
  }

  let normalized: string;
  if (decimal === null) {
    const separator = hasComma ? "," : ".";
    if ((hasComma || hasDot) && !new RegExp(`^\\d{1,3}(\\${separator}\\d{3})+$`).test(text)) {
      return null;
    }
    normalized = text.replace(/[.,]/g, "");
  } else {
    const thousands = decimal === "," ? "." : ",";
    const [whole, fraction, ...rest] = text.split(thousands).join("").split(decimal);
    if (rest.length > 0) {
      return null;
    }
    normalized = fraction === undefined ? whole : `${whole}.${fraction}`;
  }

  if (!/^\d*\.?\d+$/.test(normalized)) {
    return null;
  }
  const value = Number(normalized);
  return Number.isFinite(value) ? value : null;
}

/**
 * Read a number however it was typed: "$1,204.50", "1.130,00 €", "(250)",
 * "980-" (SAP's trailing minus), "12.5%", "NGN 45,000", "1 234 567", and even
 * "1,2O0" with a letter O for a zero. Returns null for anything that is not a
 * number, so text such as "Q1" or "2024-01-05" is left alone.
 */
export function parseLooseNumber(input: CellValue, style: NumberStyle = "us"): LooseNumber | null {
  if (typeof input === "number") {
    return Number.isFinite(input)
      ? { value: input, percent: false, currency: null, repaired: false }
      : null;
  }
  if (typeof input !== "string") {
    return null;
  }

  let text = cleanText(input);
  if (text === "" || PLACEHOLDER.test(text)) {
    return null;
  }

  let negative = false;
  let percent = false;
  let currency: string | null = null;

  if (/^\(.*\)$/.test(text)) {
    negative = true;
    text = text.slice(1, -1).trim();
  }

  const code = CURRENCY_CODES.exec(text);
  if (code) {
    currency = code[1].toUpperCase();
    text = text.replace(CURRENCY_CODES, "").trim();
  }
  for (const symbol of CURRENCY_SYMBOLS) {
    if (text.includes(symbol)) {
      currency = currency ?? symbol;
      text = text.split(symbol).join("").trim();
    }
  }

  if (text.endsWith("%")) {
    percent = true;
    text = text.slice(0, -1).trim();
  }
  if (/^[-−]/.test(text)) {
    negative = !negative;
    text = text.slice(1).trim();
  } else if (text.startsWith("+")) {
    text = text.slice(1).trim();
  }
  if (/\d-$/.test(text)) {
    negative = !negative;
    text = text.slice(0, -1).trim();
  }

  // Thousands written with spaces or apostrophes: "1 234 567", "1'234".
  text = text.replace(/[\s']/g, "");

  // A letter O typed where a zero belongs, but only when digits surround it.
  const beforeRepair = text;
  let previous: string;
  do {
    previous = text;
    text = text.replace(/(\d)[oO](?=[\d.,])/g, (_match, digit: string) => `${digit}0`);
    text = text.replace(/([.,])[oO](?=\d)/g, (_match, separator: string) => `${separator}0`);
    text = text.replace(/(\d)[oO]$/g, (_match, digit: string) => `${digit}0`);
  } while (text !== previous);
  const repaired = text !== beforeRepair;

  if (!/^\d[\d.,]*$/.test(text) && !/^[.,]\d+$/.test(text)) {
    return null;
  }
  const magnitude = digitsToNumber(
    text.startsWith(".") || text.startsWith(",") ? `0${text}` : text,
    style
  );
  if (magnitude === null) {
    return null;
  }

  let value = negative ? -magnitude : magnitude;
  if (percent) {
    value /= 100;
  }
  return { value, percent, currency, repaired };
}

/**
 * Decide whether a column writes "1,234.56" or "1.234,56", from the values
 * that give it away: a comma or dot followed by one or two digits is always a
 * decimal point, and when both appear the last one is.
 */
export function detectNumberStyle(values: readonly CellValue[]): NumberStyle {
  let us = 0;
  let eu = 0;
  for (const value of values) {
    if (typeof value !== "string") {
      continue;
    }
    const digits = value
      .replace(/(\d)[oO]/g, (_match, digit: string) => `${digit}0`)
      .replace(/[^\d.,]/g, "");
    const lastComma = digits.lastIndexOf(",");
    const lastDot = digits.lastIndexOf(".");
    if (lastComma >= 0 && lastDot >= 0) {
      if (lastComma > lastDot) eu += 1;
      else us += 1;
    } else if (lastComma >= 0 && /,\d{1,2}$/.test(digits)) {
      eu += 1;
    } else if (lastDot >= 0) {
      if ((digits.match(/\./g) ?? []).length > 1) eu += 1;
      else if (/\.\d{1,2}$/.test(digits)) us += 1;
    }
  }
  return eu > us ? "eu" : "us";
}

// ---------------------------------------------------------------------------
// Dates typed as text
// ---------------------------------------------------------------------------

/**
 * For a column of dd/mm vs mm/dd dates, let the unambiguous ones decide: a
 * first part above 12 can only be a day, a second part above 12 only a day.
 */
export function detectDayFirst(values: readonly CellValue[], fallback: boolean): boolean {
  let dayFirst = 0;
  let monthFirst = 0;
  for (const value of values) {
    if (typeof value !== "string") {
      continue;
    }
    const match = /^(\d{1,2})[-/.](\d{1,2})[-/.]\d{2,4}$/.exec(cleanText(value));
    if (!match) {
      continue;
    }
    if (Number(match[1]) > 12) dayFirst += 1;
    else if (Number(match[2]) > 12) monthFirst += 1;
  }
  if (dayFirst === monthFirst) {
    return fallback;
  }
  return dayFirst > monthFirst;
}

/** A rough fingerprint of a date's written shape, to count distinct formats. */
function dateShape(text: string): string {
  return cleanText(text)
    .replace(/[A-Za-z]+/g, "a")
    .replace(/\d+/g, "9");
}

/** Excel number formats that show a date. */
function isDateFormat(format: string | undefined): boolean {
  if (!format) {
    return false;
  }
  return /[dmy]/i.test(format.replace(/\[[^\]]*\]/g, "").replace(/"[^"]*"/g, ""));
}

// ---------------------------------------------------------------------------
// Column profiles
// ---------------------------------------------------------------------------

export type ColumnKind =
  "empty" | "number" | "currency" | "percent" | "date" | "category" | "text" | "id";

export interface ColumnProfile {
  index: number;
  header: string;
  kind: ColumnKind;
  nonBlank: number;
  distinct: number;
  currency: string | null;
  numberStyle: NumberStyle;
  dayFirst: boolean;
}

const ID_HINT =
  /(^|[\s_#.])(id|code|no|nr|number|num|ref|reference|sku|zip|postcode|postal|phone|invoice|order\s*#)($|[\s_#.])/i;
const DATE_HINT = /date|day|month|period|time|created|updated|posted|shipped|when/i;
/** Serial numbers from 1954 to 2119 - wide enough for business data, narrow enough to skip quantities. */
const SERIAL_RANGE = [20000, 80000] as const;

/**
 * Work out what a column holds. The result drives both the clean-up (which
 * cells to convert) and the dashboard (which columns to chart).
 */
export function profileColumn(
  header: string,
  values: readonly CellValue[],
  index: number,
  options: { dayFirst?: boolean; formats?: readonly (string | undefined)[] } = {}
): ColumnProfile {
  const present: CellValue[] = [];
  const presentFormats: (string | undefined)[] = [];
  values.forEach((value, row) => {
    if (!isEmptyish(value)) {
      present.push(value);
      presentFormats.push(options.formats?.[row]);
    }
  });

  const base: ColumnProfile = {
    index,
    header,
    kind: "empty",
    nonBlank: present.length,
    distinct: 0,
    currency: null,
    numberStyle: "us",
    dayFirst: options.dayFirst ?? true,
  };
  if (present.length === 0) {
    return base;
  }

  const numberStyle = detectNumberStyle(present);
  const dayFirst = detectDayFirst(present, options.dayFirst ?? true);
  const hintsDate = DATE_HINT.test(header);

  let numbers = 0;
  let percents = 0;
  let dates = 0;
  let years = 0;
  let integers = 0;
  const currencies = new Map<string, number>();
  const distinct = new Set<string>();

  present.forEach((value, i) => {
    distinct.add(typeof value === "string" ? cleanText(value).toLowerCase() : String(value));

    if (typeof value === "number") {
      const inSerialRange = value >= SERIAL_RANGE[0] && value <= SERIAL_RANGE[1];
      if (isDateFormat(presentFormats[i]) || (hintsDate && inSerialRange)) {
        dates += 1;
        return;
      }
    } else if (
      typeof value === "string" &&
      parseFlexibleDate(cleanText(value), { dayFirst }) !== null
    ) {
      dates += 1;
      return;
    }

    const parsed = parseLooseNumber(value, numberStyle);
    if (parsed) {
      numbers += 1;
      if (parsed.percent) percents += 1;
      if (parsed.currency)
        currencies.set(parsed.currency, (currencies.get(parsed.currency) ?? 0) + 1);
      if (Number.isInteger(parsed.value)) {
        integers += 1;
        if (parsed.value >= 1900 && parsed.value <= 2100) years += 1;
      }
    }
  });

  const n = present.length;
  let kind: ColumnKind;
  if (dates / n >= 0.8) {
    kind = "date";
  } else if (numbers / n >= 0.8) {
    const currencyCount = Array.from(currencies.values()).reduce((sum, count) => sum + count, 0);
    if (ID_HINT.test(header)) kind = "id";
    // A column of years is a category to group by, not a quantity to add up.
    else if (years === numbers && integers === numbers && distinct.size <= 50) kind = "category";
    else if (percents >= numbers * 0.5) kind = "percent";
    // Exports often put the symbol on only some cells; a few is enough to call it money.
    else if (currencyCount >= numbers * 0.15) kind = "currency";
    else kind = "number";
  } else if (ID_HINT.test(header) && distinct.size >= n * 0.9) {
    // Nearly unique values under an ID-like heading; duplicated rows keep it short of 100%.
    kind = "id";
  } else if (distinct.size <= 50 && distinct.size <= Math.max(2, n * 0.6)) {
    kind = "category";
  } else {
    kind = "text";
  }

  let currency: string | null = null;
  let best = 0;
  currencies.forEach((count, symbol) => {
    if (count > best) {
      best = count;
      currency = symbol;
    }
  });

  return { ...base, kind, distinct: distinct.size, currency, numberStyle, dayFirst };
}

/** The Excel number format a cleaned column should display with. */
export function numberFormatFor(profile: ColumnProfile, values: readonly CellValue[]): string {
  switch (profile.kind) {
    case "date":
      return "yyyy-mm-dd";
    case "percent":
      return "0.0%";
    case "currency": {
      const symbol = profile.currency ?? "";
      if (symbol === "$") return "$#,##0.00";
      if (/^[A-Z]{3}$/.test(symbol)) return `"${symbol} "#,##0.00`;
      return `"${symbol}"#,##0.00`;
    }
    case "number": {
      const allIntegers = values.every(
        (value) => typeof value !== "number" || Number.isInteger(value)
      );
      return allIntegers ? "#,##0" : "#,##0.00";
    }
    default:
      return "General";
  }
}

// ---------------------------------------------------------------------------
// Finding the table
// ---------------------------------------------------------------------------

export interface TableLocation {
  /** Row of the (last) header row. */
  headerRow: number;
  /** 2 when the headings are split over two rows, the upper one merged. */
  headerRows: 1 | 2;
  firstColumn: number;
  lastColumn: number;
  /** Last row that belongs to the table, before any footnotes. */
  lastRow: number;
  /** Non-blank rows above the headings: titles, "Generated by ..." lines. */
  titleRows: number[];
  /** Footnotes below the table. */
  footerRows: number[];
}

function filled(row: readonly CellValue[]): number {
  return row.reduce<number>((count, value) => count + (isEmptyish(value) ? 0 : 1), 0);
}

function looksLikeValue(value: CellValue): boolean {
  if (typeof value === "number") return true;
  if (typeof value !== "string" || isEmptyish(value)) return false;
  const text = cleanText(value);
  return parseLooseNumber(text) !== null || parseFlexibleDate(text, { dayFirst: true }) !== null;
}

function isLabel(value: CellValue): boolean {
  return typeof value === "string" && !isEmptyish(value) && !looksLikeValue(value);
}

const NOTE =
  /^(source|note|notes|generated|printed|page\s+\d|report|confidential|prepared|exported|run\s+date|created\s+by|\*)/i;

function isNoteRow(row: readonly CellValue[]): boolean {
  const cells = row.filter((value) => !isEmptyish(value));
  if (cells.length === 0 || cells.length > 2 || typeof cells[0] !== "string") {
    return false;
  }
  const text = cleanText(cells[0]);
  return NOTE.test(text) || (cells.length === 1 && text.length >= 30);
}

/** Find where the real table sits inside a sheet that may have titles and notes around it. */
export function locateTable(input: Grid): TableLocation | null {
  const grid = rectangularize(input);
  if (grid.length === 0) {
    return null;
  }

  const counts = grid.map(filled);
  const widest = Math.max(...counts);
  if (widest === 0) {
    return null;
  }
  const threshold = Math.max(2, Math.ceil(widest * 0.5));
  const scanLimit = Math.min(grid.length, 40);

  let headerRow = -1;
  for (let r = 0; r < scanLimit && headerRow < 0; r += 1) {
    const row = grid[r];
    if (counts[r] < threshold) continue;
    const labels = row.filter(isLabel).length;
    if (labels < counts[r] * 0.6) continue;

    // A header is followed by data: a value sitting under one of its labels.
    for (let next = r + 1; next <= Math.min(grid.length - 1, r + 3); next += 1) {
      if (counts[next] < Math.max(1, Math.ceil(widest * 0.4))) continue;
      if (grid[next].some((value, c) => looksLikeValue(value) && isLabel(row[c]))) {
        headerRow = r;
      }
      break;
    }
  }
  if (headerRow < 0) {
    headerRow = counts.findIndex((count) => count >= Math.min(2, widest));
  }

  // Headings split over two rows: a sparser row of labels directly above,
  // each sitting over a heading (the merged-cell pattern).
  let headerRows: 1 | 2 = 1;
  if (headerRow > 0) {
    const above = grid[headerRow - 1];
    const aboveCount = counts[headerRow - 1];
    if (
      aboveCount >= 2 &&
      aboveCount < counts[headerRow] &&
      above.every(
        (value, c) => isEmptyish(value) || (isLabel(value) && !isEmptyish(grid[headerRow][c]))
      )
    ) {
      headerRows = 2;
    }
  }

  let lastRow = grid.length - 1;
  const footerRows: number[] = [];
  while (lastRow > headerRow) {
    if (counts[lastRow] === 0) {
      lastRow -= 1;
    } else if (isNoteRow(grid[lastRow])) {
      footerRows.unshift(lastRow);
      lastRow -= 1;
    } else {
      break;
    }
  }

  const bodyRows = Math.max(1, lastRow - headerRow);
  const used: number[] = [];
  for (let c = 0; c < grid[0].length; c += 1) {
    const inHeader =
      !isEmptyish(grid[headerRow][c]) || (headerRows === 2 && !isEmptyish(grid[headerRow - 1][c]));
    let inBody = 0;
    for (let r = headerRow + 1; r <= lastRow; r += 1) {
      if (!isEmptyish(grid[r][c])) inBody += 1;
    }
    if (inHeader || inBody / bodyRows >= 0.2) used.push(c);
  }

  const titleRows: number[] = [];
  for (let r = 0; r < headerRow - (headerRows - 1); r += 1) {
    if (counts[r] > 0) titleRows.push(r);
  }

  return {
    headerRow,
    headerRows,
    firstColumn: used.length > 0 ? Math.min(...used) : 0,
    lastColumn: used.length > 0 ? Math.max(...used) : grid[0].length - 1,
    lastRow,
    titleRows,
    footerRows,
  };
}

/**
 * Turn one or two heading rows into unique, non-empty column names. A merged
 * upper heading ("Q1" over Jan/Feb/Mar) is carried across its blank cells and
 * joined on: "Q1 Jan".
 */
export function buildHeaders(
  upper: readonly CellValue[] | null,
  main: readonly CellValue[]
): { headers: string[]; renamed: string[] } {
  let carry = "";
  const renamed: string[] = [];
  const taken: string[] = [];
  const headers = main.map((cell, c) => {
    if (upper) {
      const top = upper[c];
      if (!isEmptyish(top)) carry = cleanText(String(top));
    }
    const label = isEmptyish(cell) ? "" : cleanText(String(cell));
    let header = upper && carry ? (label ? `${carry} ${label}` : carry) : label;
    if (header === "") {
      header = `Column ${columnLetter(c)}`;
      renamed.push(header);
    }
    const unique = uniqueName(header, taken);
    if (unique !== header) renamed.push(unique);
    taken.push(unique);
    return unique;
  });
  return { headers, renamed };
}

// ---------------------------------------------------------------------------
// Rows that are not data
// ---------------------------------------------------------------------------

export type RowKind = "data" | "blank" | "repeatedHeader" | "total" | "section";

/** "Total", "Grand Total", "Sub-total", "Europe Total", "Total: " - but never "Total Foods Ltd". */
const TOTAL_CELL =
  /^(?:grand\s+|sub\s*-?\s*)?totals?\s*:?$|\s(?:sub\s*-?\s*)?totals?\s*:?$|^totals?\s*[:\-–]/i;

export function classifyRow(
  row: readonly CellValue[],
  headerKeys: readonly string[],
  width: number
): RowKind {
  const present = row.filter((value) => !isEmptyish(value));
  if (present.length === 0) {
    return "blank";
  }

  const headerCount = headerKeys.filter((key) => key !== "").length;
  if (headerCount > 0) {
    const matches = row.filter(
      (value, c) => headerKeys[c] && normalizeHeader(value) === headerKeys[c]
    ).length;
    if (matches >= Math.max(2, headerCount * 0.7)) return "repeatedHeader";
  }

  const texts = present
    .filter((value): value is string => typeof value === "string")
    .map(cleanText);
  if (texts.some((text) => TOTAL_CELL.test(text)) && present.some(looksLikeValue)) {
    return "total";
  }

  if (present.length === 1 && typeof present[0] === "string" && width >= 3) {
    const text = cleanText(present[0]);
    if (text.length <= 40 && !looksLikeValue(text)) return "section";
  }

  return "data";
}

/** "Region: Europe" becomes a "Region" column holding "Europe". */
export function splitSectionLabel(text: string): { name: string | null; value: string } {
  const match = /^([^:]{2,24}):\s*(.+)$/.exec(cleanText(text));
  return match
    ? { name: match[1].trim(), value: match[2].trim() }
    : { name: null, value: cleanText(text) };
}

// ---------------------------------------------------------------------------
// Spellings
// ---------------------------------------------------------------------------

function spellingKey(text: string): string {
  return cleanText(text)
    .toLowerCase()
    .replace(/[^a-z0-9\u00C0-\u024F]+/g, "");
}

/** Edit distance, stopping early once it exceeds `limit`. */
export function editDistance(a: string, b: string, limit = 3): number {
  if (Math.abs(a.length - b.length) > limit) return limit + 1;
  let previous = Array.from({ length: b.length + 1 }, (_value, j) => j);
  for (let i = 1; i <= a.length; i += 1) {
    const current = [i];
    let best = i;
    for (let j = 1; j <= b.length; j += 1) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      current[j] = Math.min(previous[j] + 1, current[j - 1] + 1, previous[j - 1] + cost);
      best = Math.min(best, current[j]);
    }
    if (best > limit) return limit + 1;
    previous = current;
  }
  return previous[b.length];
}

/** Prefer "North America" over "north america" or "NORTH AMERICA" when counts tie. */
function spellingQuality(text: string): number {
  if (text === text.toLowerCase() || text === text.toUpperCase()) return 0;
  return 1;
}

/**
 * Group spellings of the same thing - different case, spacing, punctuation,
 * or a one-letter typo - and map each to the most common spelling.
 */
export function unifySpellings(values: readonly CellValue[]): Map<string, string> {
  const counts = new Map<string, number>();
  for (const value of values) {
    if (typeof value === "string" && !isEmptyish(value)) {
      const text = cleanText(value);
      counts.set(text, (counts.get(text) ?? 0) + 1);
    }
  }

  // Group by key first, then fold keys that are one or two typos apart.
  const groups = new Map<string, string[]>();
  counts.forEach((_count, text) => {
    const key = spellingKey(text);
    if (key === "") return;
    groups.set(key, [...(groups.get(key) ?? []), text]);
  });

  const keys = Array.from(groups.keys()).sort(
    (a, b) =>
      groups.get(b)!.reduce((s, t) => s + counts.get(t)!, 0) -
      groups.get(a)!.reduce((s, t) => s + counts.get(t)!, 0)
  );
  const parent = new Map<string, string>();
  for (let i = 0; i < keys.length; i += 1) {
    if (parent.has(keys[i])) continue;
    for (let j = i + 1; j < keys.length; j += 1) {
      if (parent.has(keys[j])) continue;
      const a = keys[i];
      const b = keys[j];
      const shortest = Math.min(a.length, b.length);
      // Short codes differ meaningfully by one letter ("UK"/"US"), so only fold longer words.
      const allowed = shortest >= 10 ? 2 : shortest >= 6 ? 1 : 0;
      // Codes with digits ("SO-5001", "SKU 12") are never typos of each other.
      if (allowed > 0 && !/\d/.test(a) && !/\d/.test(b) && editDistance(a, b, allowed) <= allowed) {
        parent.set(b, a);
      }
    }
  }

  const clusters = new Map<string, string[]>();
  groups.forEach((texts, key) => {
    const root = parent.get(key) ?? key;
    clusters.set(root, [...(clusters.get(root) ?? []), ...texts]);
  });

  const mapping = new Map<string, string>();
  clusters.forEach((texts) => {
    if (texts.length < 2) return;
    // The most-used spelling group wins ("Wholesale" over the typo "Wholsale"),
    // then the best-cased spelling within it ("Online" over "online").
    const keyCount = new Map<string, number>();
    for (const text of texts) {
      const key = spellingKey(text);
      keyCount.set(key, (keyCount.get(key) ?? 0) + counts.get(text)!);
    }
    const canonical = texts
      .slice()
      .sort(
        (a, b) =>
          keyCount.get(spellingKey(b))! - keyCount.get(spellingKey(a))! ||
          spellingQuality(b) - spellingQuality(a) ||
          counts.get(b)! - counts.get(a)!
      )[0];
    for (const text of texts) {
      if (text !== canonical) mapping.set(text, canonical);
    }
  });
  return mapping;
}

// ---------------------------------------------------------------------------
// The whole pipeline
// ---------------------------------------------------------------------------

export type FindingId =
  | "titleRows"
  | "footerRows"
  | "twoRowHeader"
  | "headers"
  | "blankRows"
  | "repeatedHeaders"
  | "totals"
  | "sections"
  | "spaces"
  | "placeholders"
  | "textNumbers"
  | "textDates"
  | "spellings"
  | "duplicates"
  | "emptyColumns";

export interface TidyFinding {
  id: FindingId;
  /** What was wrong, in the user's words. */
  label: string;
  /** What fixing it does. */
  fix: string;
  count: number;
  examples: string[];
  /** Structural fixes (finding the table) always apply; the rest can be switched off. */
  optional: boolean;
}

export interface TidyOptions {
  /** Fixes the user switched off. */
  skip?: ReadonlySet<FindingId>;
  /** Fallback for dates like 03/04/2024 when a column gives no clue. */
  dayFirst?: boolean;
  /** Excel number formats of the source cells, to recognise real dates. */
  formats?: readonly (readonly string[])[];
}

export interface TidyResult {
  headers: string[];
  rows: Grid;
  columns: ColumnProfile[];
  numberFormats: string[];
  findings: TidyFinding[];
  location: TableLocation;
  /** Rows in the source, before anything was removed. */
  sourceRows: number;
}

/** The highest-scoring examples, one per written shape, so the list shows variety. */
function pickExamples(
  candidates: ReadonlyArray<{ text: string; score: number; shape: string }>
): string[] {
  const shapes = new Set<string>();
  const picked: string[] = [];
  for (const candidate of candidates.slice().sort((a, b) => b.score - a.score)) {
    if (shapes.has(candidate.shape)) continue;
    shapes.add(candidate.shape);
    picked.push(candidate.text);
    if (picked.length === 4) break;
  }
  return picked;
}

function sample<T>(items: readonly T[], size = 3): T[] {
  return items.slice(0, size);
}

function show(value: CellValue): string {
  return typeof value === "string"
    ? `"${value.length > 24 ? `${value.slice(0, 22)}...` : value}"`
    : String(value);
}

/**
 * Find the table and repair it. Returns the clean table plus a list of every
 * kind of problem found, with counts and examples, whether or not its fix was
 * applied - so the same call powers the preview and the real run.
 */
export function tidyTable(input: Grid, options: TidyOptions = {}): TidyResult | null {
  const grid = rectangularize(input);
  const location = locateTable(grid);
  if (!location) {
    return null;
  }
  const skip = options.skip ?? new Set<FindingId>();
  const applies = (id: FindingId) => !skip.has(id);
  const findings: TidyFinding[] = [];
  const add = (finding: Omit<TidyFinding, "optional">, optional = true) => {
    if (finding.count > 0) findings.push({ ...finding, optional });
  };

  const { headerRow, headerRows, firstColumn, lastColumn, lastRow } = location;
  const slice = (row: readonly CellValue[]) => row.slice(firstColumn, lastColumn + 1);
  const width = lastColumn - firstColumn + 1;

  add(
    {
      id: "titleRows",
      label: "Title rows above the table",
      fix: "Skipped, so the table starts at its real headings.",
      count: location.titleRows.length,
      examples: sample(
        location.titleRows.map((r) => show(grid[r].find((v) => !isEmptyish(v)) ?? ""))
      ),
    },
    false
  );
  add(
    {
      id: "footerRows",
      label: "Notes below the table",
      fix: "Left out of the data.",
      count: location.footerRows.length,
      examples: sample(
        location.footerRows.map((r) => show(grid[r].find((v) => !isEmptyish(v)) ?? ""))
      ),
    },
    false
  );

  const upper = headerRows === 2 ? slice(grid[headerRow - 1]) : null;
  const { headers: baseHeaders, renamed } = buildHeaders(upper, slice(grid[headerRow]));
  if (upper) {
    add(
      {
        id: "twoRowHeader",
        label: "Headings split over two rows",
        fix: "Joined into one heading row.",
        count: 1,
        examples: sample(baseHeaders.filter((header) => header.includes(" "))),
      },
      false
    );
  }
  add(
    {
      id: "headers",
      label: "Missing or repeated column names",
      fix: "Given unique names.",
      count: renamed.length,
      examples: sample(renamed),
    },
    false
  );

  // --- Rows -----------------------------------------------------------------
  const headerKeys = slice(grid[headerRow]).map((cell) =>
    isEmptyish(cell) ? "" : normalizeHeader(cell)
  );
  const kept: CellValue[][] = [];
  const sectionOf: (string | null)[] = [];
  const blankRows: number[] = [];
  const repeated: number[] = [];
  const totals: CellValue[][] = [];
  const sectionLabels: string[] = [];
  let sectionName: string | null = null;
  let currentSection: string | null = null;

  for (let r = headerRow + 1; r <= lastRow; r += 1) {
    const row = slice(grid[r]);
    const kind = classifyRow(row, headerKeys, width);
    if (kind === "blank") {
      blankRows.push(r);
      continue;
    }
    if (kind === "repeatedHeader") {
      repeated.push(r);
      continue;
    }
    if (kind === "total") {
      totals.push(row);
      if (applies("totals")) continue;
    }
    if (kind === "section") {
      const label = splitSectionLabel(String(row.find((value) => !isEmptyish(value))));
      sectionLabels.push(label.value);
      sectionName = sectionName ?? label.name;
      currentSection = label.value;
      if (applies("sections")) continue;
    }
    kept.push([...row]);
    sectionOf.push(currentSection);
  }

  add(
    {
      id: "blankRows",
      label: "Empty rows",
      fix: "Removed.",
      count: blankRows.length,
      examples: [],
    },
    false
  );
  add(
    {
      id: "repeatedHeaders",
      label: "Heading rows repeated inside the data",
      fix: "Removed.",
      count: repeated.length,
      examples: [],
    },
    false
  );
  add({
    id: "totals",
    label: "Total and subtotal rows mixed into the data",
    fix: "Removed, so totals aren't counted twice in charts and sums.",
    count: totals.length,
    examples: sample(
      totals.map((row) =>
        show(row.find((v) => typeof v === "string" && TOTAL_CELL.test(cleanText(v))) ?? "")
      )
    ),
  });

  let headers = baseHeaders;
  const useSections = applies("sections") && sectionLabels.length > 0 && kept.length > 0;
  add({
    id: "sections",
    label: "Group headings inside the table",
    fix: `Moved into their own "${sectionName ?? "Group"}" column, filled in for every row.`,
    count: sectionLabels.length,
    examples: sample(sectionLabels.map((label) => show(label))),
  });
  if (useSections) {
    const name = uniqueName(sectionName ?? "Group", headers);
    headers = [name, ...headers];
    kept.forEach((row, i) => row.unshift(sectionOf[i]));
  }

  const columnCount = headers.length;
  const rows: CellValue[][] = kept.map((row) => padRow(row, columnCount));

  // --- Cells ----------------------------------------------------------------
  const spaceFixes: string[] = [];
  let spaceCount = 0;
  if (applies("spaces")) {
    rows.forEach((row) =>
      row.forEach((value, c) => {
        if (typeof value === "string") {
          const cleaned = cleanText(value);
          if (cleaned !== value) {
            spaceCount += 1;
            if (spaceFixes.length < 3) spaceFixes.push(show(value));
            row[c] = cleaned;
          }
        }
      })
    );
  } else {
    rows.forEach((row) =>
      row.forEach((value) => {
        if (typeof value === "string" && cleanText(value) !== value) spaceCount += 1;
      })
    );
  }
  add({
    id: "spaces",
    label: "Extra and invisible spaces",
    fix: "Trimmed.",
    count: spaceCount,
    examples: spaceFixes,
  });

  // Map source-row formats onto the kept rows, when we have them, so real
  // Excel dates in a date-formatted column are recognised.
  const formatColumn = (c: number): (string | undefined)[] | undefined => {
    if (!options.formats) return undefined;
    const sourceColumn = c - (useSections ? 1 : 0) + firstColumn;
    if (sourceColumn < firstColumn) return undefined;
    // Only the first data row's format is a reliable guide per column.
    const first = options.formats[headerRow + 1]?.[sourceColumn];
    return rows.map(() => first);
  };

  const columns = headers.map((header, c) =>
    profileColumn(
      header,
      rows.map((row) => row[c]),
      c,
      { dayFirst: options.dayFirst, formats: formatColumn(c) }
    )
  );

  let placeholderCount = 0;
  // Show the most telling examples: typo repairs, negatives, currencies, separators.
  const numberCandidates: Array<{ text: string; score: number; shape: string }> = [];
  let numberCount = 0;
  const dateExamples: string[] = [];
  let dateCount = 0;
  const dateShapes = new Set<string>();

  columns.forEach((profile, c) => {
    const numeric =
      profile.kind === "number" || profile.kind === "currency" || profile.kind === "percent";
    if (!numeric && profile.kind !== "date") return;

    rows.forEach((row) => {
      const value = row[c];
      if (isPlaceholder(value)) {
        placeholderCount += 1;
        if (applies("placeholders")) row[c] = null;
        return;
      }
      if (typeof value !== "string" || isBlankCell(value)) return;

      if (numeric) {
        const parsed = parseLooseNumber(value, profile.numberStyle);
        if (parsed) {
          numberCount += 1;
          numberCandidates.push({
            text: `${show(value)} → ${parsed.value.toLocaleString("en-US")}`,
            score:
              (parsed.repaired ? 8 : 0) +
              (parsed.value < 0 ? 4 : 0) +
              (parsed.currency ? 2 : 0) +
              (/[.,]\d{3}/.test(value) ? 1 : 0),
            shape: cleanText(value).replace(/\d+/g, "9"),
          });
          if (applies("textNumbers")) row[c] = parsed.value;
        }
      } else {
        const parsed = parseFlexibleDate(cleanText(value), { dayFirst: profile.dayFirst });
        if (parsed) {
          dateCount += 1;
          dateShapes.add(dateShape(value));
          if (dateExamples.length < 3) dateExamples.push(show(value));
          if (applies("textDates")) row[c] = dateToExcelSerial(parsed);
        }
      }
    });
  });

  add({
    id: "placeholders",
    label: 'Placeholders like "N/A" and "-" in number or date columns',
    fix: "Emptied, so they don't break sums.",
    count: placeholderCount,
    examples: [],
  });
  add({
    id: "textNumbers",
    label: "Numbers stored as text",
    fix: "Turned into real numbers: currency signs, thousands separators, brackets and trailing minus signs understood.",
    count: numberCount,
    examples: pickExamples(numberCandidates),
  });
  add({
    id: "textDates",
    label:
      dateShapes.size > 1
        ? `Dates typed as text, in ${dateShapes.size} different formats`
        : "Dates typed as text",
    fix: "Turned into real dates, all shown the same way.",
    count: dateCount,
    examples: dateExamples,
  });

  let spellingCount = 0;
  const spellingExamples: string[] = [];
  columns.forEach((profile, c) => {
    // Only columns of repeated labels: free text and IDs are left exactly as typed.
    if (profile.kind !== "category") return;
    const mapping = unifySpellings(rows.map((row) => row[c]));
    if (mapping.size === 0) return;
    const byTarget = new Map<string, string[]>();
    mapping.forEach((to, from) => byTarget.set(to, [...(byTarget.get(to) ?? []), from]));
    byTarget.forEach((froms, to) => {
      if (spellingExamples.length < 3)
        spellingExamples.push(`${froms.map((f) => show(f)).join(", ")} → ${show(to)}`);
    });
    rows.forEach((row) => {
      const value = row[c];
      if (typeof value === "string" && mapping.has(cleanText(value))) {
        spellingCount += 1;
        if (applies("spellings")) row[c] = mapping.get(cleanText(value))!;
      }
    });
  });
  add({
    id: "spellings",
    label: "The same thing spelled different ways",
    fix: "Changed to the most common spelling, so each one counts as a single group.",
    count: spellingCount,
    examples: spellingExamples,
  });

  // --- Duplicates and empty columns ------------------------------------------
  const seen = new Set<string>();
  const unique: CellValue[][] = [];
  let duplicates = 0;
  for (const row of rows) {
    const key = JSON.stringify(row);
    if (seen.has(key)) {
      duplicates += 1;
      if (applies("duplicates")) continue;
    }
    seen.add(key);
    unique.push(row);
  }
  add({
    id: "duplicates",
    label: "Duplicate rows",
    fix: "Removed, keeping the first.",
    count: duplicates,
    examples: [],
  });

  const emptyColumns = columns.filter(
    (profile) => profile.kind === "empty" && /^Column [A-Z]+/.test(profile.header)
  );
  add({
    id: "emptyColumns",
    label: "Empty columns",
    fix: "Removed.",
    count: emptyColumns.length,
    examples: sample(emptyColumns.map((profile) => profile.header)),
  });

  const keepColumn = columns.map(
    (profile) => !(applies("emptyColumns") && emptyColumns.includes(profile))
  );
  const finalHeaders = headers.filter((_h, c) => keepColumn[c]);
  const finalRows = unique.map((row) => row.filter((_v, c) => keepColumn[c]));
  const finalColumns = columns
    .filter((_p, c) => keepColumn[c])
    .map((profile, index) => ({ ...profile, index }));

  return {
    headers: finalHeaders,
    rows: finalRows,
    columns: finalColumns,
    numberFormats: finalColumns.map((profile) =>
      numberFormatFor(
        profile,
        finalRows.map((row) => row[profile.index])
      )
    ),
    findings,
    location,
    sourceRows: grid.length,
  };
}

/** Total number of individual problems, for a headline like "47 problems found". */
export function countProblems(findings: readonly TidyFinding[]): number {
  return findings.reduce((sum, finding) => sum + finding.count, 0);
}

// ---------------------------------------------------------------------------
// Office.js drivers
// ---------------------------------------------------------------------------

interface SourceGrid {
  values: Grid;
  formats: string[][];
  name: string;
  address: string;
}

async function readSourceGrid(
  context: Excel.RequestContext,
  ref: DataSourceRef
): Promise<SourceGrid | null> {
  let range: Excel.Range;
  if (ref.kind === "selection") {
    const selection = await loadSelectedRange(context);
    range =
      selection.rowCount === 1 && selection.columnCount === 1
        ? context.workbook.worksheets.getActiveWorksheet().getUsedRangeOrNullObject(true)
        : selection;
  } else if (ref.kind === "table") {
    range = context.workbook.tables.getItem(ref.name).getRange();
  } else {
    range = context.workbook.worksheets.getItem(ref.name).getUsedRangeOrNullObject(true);
  }
  range.load(["values", "numberFormat", "address", "worksheet/name"]);
  await context.sync();
  if (range.isNullObject) {
    return null;
  }
  return {
    values: range.values as Grid,
    formats: range.numberFormat as string[][],
    name: ref.kind === "table" ? ref.name : range.worksheet.name,
    address: range.address,
  };
}

export interface TidyPreview {
  result: TidyResult | null;
  sourceName: string;
}

/** Scan a sheet, table or selection and report what's wrong, without changing anything. */
export async function previewTidy(ref: DataSourceRef, dayFirst = true): Promise<TidyPreview> {
  try {
    return await Excel.run(async (context) => {
      const source = await readSourceGrid(context, ref);
      if (!source) {
        return { result: null, sourceName: ref.name };
      }
      return {
        result: tidyTable(source.values, { dayFirst, formats: source.formats }),
        sourceName: source.name,
      };
    });
  } catch {
    return { result: null, sourceName: ref.name };
  }
}

/** Write the repaired table to a new sheet as a formatted Excel table. The source is not touched. */
export async function tidyToNewSheet(
  ref: DataSourceRef,
  skip: ReadonlySet<FindingId>,
  dayFirst = true
): Promise<{ result: OperationResult; sheetName: string | null }> {
  let sheetName: string | null = null;
  const result = await runExcel(async (context) => {
    const source = await readSourceGrid(context, ref);
    if (!source) {
      return fail("There's no data there. Pick a sheet or select your table and try again.");
    }
    const tidy = tidyTable(source.values, { skip, dayFirst, formats: source.formats });
    if (!tidy || tidy.rows.length === 0) {
      return fail("Couldn't find a table with headings and data rows in that range.");
    }

    const sheet = await createSheetWithUniqueName(context, `${source.name} (clean)`);
    const grid: Grid = [tidy.headers, ...tidy.rows];
    const formats = grid.map((_row, r) =>
      r === 0 ? tidy.headers.map(() => "General") : tidy.numberFormats
    );
    await writeGridWithFormats(context, sheet, 0, 0, grid, formats);

    const table = sheet.tables.add(
      sheet.getRangeByIndexes(0, 0, grid.length, tidy.headers.length),
      true /* hasHeaders */
    );
    table.name = `MExClean_${Date.now()}`;
    sheet.getUsedRange().format.autofitColumns();
    sheet.freezePanes.freezeRows(1);
    sheet.activate();
    await context.sync();
    sheetName = sheet.name;

    const applied = tidy.findings.filter((finding) => !skip.has(finding.id));
    return ok(
      `Clean table on "${sheet.name}": ${plural(tidy.rows.length, "row")}, ${plural(tidy.headers.length, "column")}. Your original is unchanged.`,
      applied.map((finding) => `${finding.label}: ${finding.count.toLocaleString()} fixed`)
    );
  });
  return { result, sheetName };
}
